# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/mail.gobitsnbytes.org
cert = /etc/letsencrypt/live/mail.gobitsnbytes.org/cert.pem
privkey = /etc/letsencrypt/live/mail.gobitsnbytes.org/privkey.pem
chain = /etc/letsencrypt/live/mail.gobitsnbytes.org/chain.pem
fullchain = /etc/letsencrypt/live/mail.gobitsnbytes.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = b1aaabfcfd0802176dcf7aa81f9b3e87
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
===
# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/auth.gobitsnbytes.org
cert = /etc/letsencrypt/live/auth.gobitsnbytes.org/cert.pem
privkey = /etc/letsencrypt/live/auth.gobitsnbytes.org/privkey.pem
chain = /etc/letsencrypt/live/auth.gobitsnbytes.org/chain.pem
fullchain = /etc/letsencrypt/live/auth.gobitsnbytes.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = b1aaabfcfd0802176dcf7aa81f9b3e87
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
===
# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/cal.gobitsnbytes.org
cert = /etc/letsencrypt/live/cal.gobitsnbytes.org/cert.pem
privkey = /etc/letsencrypt/live/cal.gobitsnbytes.org/privkey.pem
chain = /etc/letsencrypt/live/cal.gobitsnbytes.org/chain.pem
fullchain = /etc/letsencrypt/live/cal.gobitsnbytes.org/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = b1aaabfcfd0802176dcf7aa81f9b3e87
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
